name : Pushing docker image to ECR

on: [push]

jobs:
  aws-ecr-image:
    runs-on: self-hosted
    defaults:
        run:
            shell: bash
    steps:

        - name: git checkout
          uses: actions/checkout@v3
        - name: Assigning date to a variable
          id: date
          run: |
            echo "DATE=$(date +%d%m%y_%H%M%S)" >> $GITHUB_OUTPUT

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, tag, and push docker image to Amazon ECR
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: nginx
            IMAGE_TAG: ${{ steps.date.outputs.DATE }}
          run: |
            pwd
            ls -la
            echo "==================================================="
            ls -la /home/ec2-user/actions-runner/_work/github-actions
            docker build -t $REGISTRY/$REPOSITORY:v_$IMAGE_TAG .infra/nginx/dev/
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG