name : Appending date to file name

on: [push]

jobs:
  appending-date:
    runs-on: self-hosted
    defaults:
        run:
            shell: bash
    steps:
        - name: Assigning date to a variable
          id: date
          run: |
            echo "DATE=$(date +%d%m%y_%H%M%S)" >> $GITHUB_OUTPUT

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, tag, and push docker image to Amazon ECR
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: nginx
            IMAGE_TAG: ${{ steps.date.outputs.DATE }}
          run: |
            docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .infra/nodejs/dev/Dockerfile
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG