name: Getting IP info

on: [push, pull_request]

jobs:
  Getting-IP-Info:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2
        echo ${{ steps.ip.outputs.ipv4 }}
