name: Accessing s3 using roles

on: [push]

jobs:
  Accessing-s3-info:
    name: Testing s3 bucket access
    runs-on: self-hosted
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: s3_role_testing
          role-duration-seconds: 1200
          aws-region: us-east-1

      - name: Getting s3 bucket List
        run: aws s3 ls

